カーネル報告
rt-net/RaspberryPiMouse-Wiki pull request #2
Opened 2020-04-07 00:20 UTC by shu-rt

以下のカーネルバージョン
5.3.0-1017-raspi2
及び
5.3.0-1021-raspi2
でラズパイが正常に動作したことを確認したため報告いたします。

2020-04-07 10:25 UTC, Tiryoh requested changes
報告ありがとうございます！
いまのところ32bitか64bitかのどちらか一方のカーネルでしかデバイスドライバが動かなかったことはないのですが、今後のために`aarch64`なのか`armhf`なのかわかるように記載お願いします。

2020-04-07 10:25 UTC, Tiryoh commented on Home.md
> +  5.3.0-1017-raspi2
ここも`uname -a`の結果（32bit版64bit版なのか）をお願いします。

2020-04-08 08:49 UTC, shu-rt commented on Home.md
> +  5.3.0-1017-raspi2
バージョンが上がってしまっているので、再現できるか試してみます。

2020-04-08 08:57 UTC, shu-rt commented on Home.md
> +  5.3.0-1017-raspi2
見れました
Linux ubuntu 5.3.0-1017-raspi2 #19~18.04.1-Ubuntu SMP Fri Jan 17 11:14:07 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
でした。再度動作確認を行います。

2020-04-08 10:57 UTC, shu-rt commented on Home.md
> +  5.3.0-1017-raspi2
カーネルバージョンがごちゃごちゃしちゃっているので
再度確認できてからもう一度プルリク投げます。

2020-04-08 10:57 UTC, closed without merging